source 'https://rubygems.org'

gem 'rails',          '4.1.0'
gem 'activeresource', '4.0.0'

gem 'sqlite3',        '1.3.9'

gem 'daylight',       '0.9.0.rc1', path: '../..'

gem 'rspec-rails', '~> 2.14.0'
gem 'artifice',    '~> 0.6'
