source 'https://rubygems.org'

gem 'rails',          '4.1.0'
gem 'activeresource', '4.0.0'

gem 'sqlite3',        '1.3.9'

gem 'daylight',       path: '../..'

group :test do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'artifice',    '~> 0.6'
end
